//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aloiCRUDapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class aloi_projdetails
    {
        public int ID { get; set; }


        [Required(ErrorMessage = "Required")]
        [MaxLength(50)]
        public string full_name { get; set; }
        
        public string opt_address { get; set; }

        
        [Required(ErrorMessage = "Required")]
        public int phone_number { get; set; }


        [Required(ErrorMessage = "Required")]
        public bool fund_request { get; set; }
        
        
        public Nullable<int> fund_amount { get; set; }


        public string fund_purpose { get; set; }


        
        public string business_type { get; set; }
    }
}
